### ISSUE TITLE
Покупатель знакомится с описанием книги

### ISSUE THREAD

**Issue by hlebwritescode** [GlebTheProgrammer/Store#4]
Как *покупатель* я могу ознакомиться с детальным описанием книги, чтобы принять решение о покупке.

## Основной сценарий
1. Покупатель выбирает книги из списка найденных книг.
2. Сайт показывает детальное описание.

**Comment by GlebTheProgrammer** [comment]
1. Добавить поле 'Price' к книге.
2. Почистить HTML.

**Comment by hlebwritescode** [comment]
1. Добавить поле `Price` к книге.
2. Почистить HTML.
